const nativeLanguageForms = {
	"Abaza":	"абаза бызшва",
	"Abenaki":	"Alnôba",
	"Abkhaz":	"аҧсуа бызшәа",
	"Adyghe":	"адыгэбзэ",
	"Afar":	"ʿAfár af",
	"Afrikaans":	"Afrikaans",
	"Ainu":	"アイヌ イタク",
	"Akan":	"akan",
	"Albanian":	"shqip",
	"Aleut":	"Unangam tunuu",
	"Amharic":	"ኣማርኛ",
	"Apache":	"Ndéé",
	"Arabic":	" العربية",
	"Aragonese":	"Fabla / l’Aragonés",
	"Aramaic ":	"לשנא ארמיא",
	"Aramaic ":	"ܠܫܢܐ ܤܘܪܝܝܐ",
	"Aramaic ":	"ܐܬܘܪܝܐ ܣܘܪܬ",
	"Aranese":	"Aranés",
	"Arapaho":	"Hinono’eitiit",
	"Argobba":	"አዓርጎባ ኣፍ",
	"Armenian":	"Հայերէն",
	"Aromanian ":	"Armãneashti",
	"Arrernte":	"Arrernte angkentye",
	"Assamese":	"অসমীয়া ",
	"Asturian":	"Asturianu",
	"Avar":	"магIарул мацI ",
	"Awngi":	"አውጚ",
	"Aymara":	"aymar aru",
	"Azerbaijani":	"Азәрбајҹан дили / آذربايجانجا ديلي",
	"Balinese":	"Basa Bali",
	"Balkar ":	"малкъар/балкъар",
	"Baluchi":	"بلوچی",
	"Bambara":	"Bamanankan",
	"Bashkir":	"башҡорт теле",
	"Bassa":	"ɓasaá",
	"Basque":	"euskara",
	"Beja":	"Badāwīyä / بداوية",
	"Belarusian":	"Беларуская мова ",
	"Bemba":	"iciBemba / ciBemba / ichiBemba / chiBemba",
	"Bengali":	"বাংলা ",
	"Berber":	"Tamazight",
	"Bhojpuri":	"भोजपुरी ",
	"Blin":	"ብሊን ",
	"Blackfoot":	"ᑯᖾᖹ / ᖿᐟᖻᐟ / ᓱᖽᐧᖿ ",
	"Bosnian":	"bosanski / босански / بۉسانسقى",
	"Breton":	"ar brezhoneg / brezhoneg",
	"Buginese":	"ᨅᨔ ᨕᨘᨁᨗ ",
	"Buhid":	"ᝊᝓᝑᝒᝇ ",
	"Bulgarian":	"български ",
	"Burmese":	"ဗမာစကား ",
	"Buryat":	"буряад хэлэн ",
	"Carrier":	"ᑐᑊᘁᗕᑋᗸ ",
	"Catalan":	"català",
	"Cayuga":	"Goyogo̱hó:nǫ’",
	"Cebuano":	"Sinugboanon / Sugboanon",
	"Chagatai":	"جغتای",
	"Chaha":	"ቸሃ",
	"Chamorro":	"chamoru",
	"Chechen":	"Нохчийн мотт ",
	"Cherokee":	"ᏣᎳᎩ ",
	"Cheyenne":	"Tsėhesenėstsestotse / Tsisinstsistots",
	"Chichewa":	"Chicheŵa",
	"Chickasaw":	"Chikasha",
	"Chinese":	"中文 ",
	"Chipewyan":	"Dëne Sųłiné / ᑌᓀᓲᒢᕄᓀ",
	"Choctaw":	"Chahta Anumpa",
	"Comanche":	"numu tekwapu",
	"Cornish":	"Kernewek / Kernowek / Kernuak / Curnoack",
	"Corsican":	"corsu",
	"Cree":	"ᓀᐦᐃᔭᐍᐏᐣ ",
	"Creek":	"Maskoki / Mvskokē empunakv",
	"Croatian":	"Hrvatski",
	"Czech":	"čeština / český jazyk",
	"Dakota":	"Dakȟótiyapi – Yankton Dakota",
	"Dangme":	"adangbɛ",
	"Danish":	"dansk",
	"Dargwa":	"дарган мез ",
	"Dari":	"درى",
	"Dinka":	"Thuɔŋjäŋ",
	"Dungan":	"хуэйзў йүян ",
	"Dutch":	"Nederlands",
	"Dzongkha /":	"རྫོང་ཁ ",
	"Erzya":	"эрзянь кель ",
	"Estonian":	"eesti keel",
	"Ewe":	"Eʋegbe",
	"Eyak":	"I·ya·q",
	"Faroese":	"Føroyskt",
	"Fijian":	"Vakaviti",
	"Finnish":	"suomi",
	"Flemish":	"Vlaams",
	"Fon":	"fɔngbè",
	"French":	"français",
	"Frisian ":	"Frysk",
	"Friulan":	"furlan / marilenghe",
	"Fula":	"fulfulde",
	"Ga":	"Gã",
	"Galician":	"Galego",
	"Ganda":	"LùGáànda",
	"Ge’ez":	"ግዕዝ ",
	"Genoese":	"zeneize / zeneisei",
	"Georgian":	"ქართული ",
	"German":	"Deutsch",
	"Godoberi":	"ГъибдилӀи мицци",
	"Gooniyandi":	"Guniandi",
	"Greek":	"ελληνικά ",
	"Greenlandic":	"Kalaallisut / Kalaallit oqaasii",
	"Guernsey Norman":	"Dgèrnésiais",
	"Guarani":	"Avañe’ẽ",
	"Gujarati":	"ગુજરાતી ",
	"Gwich’in":	"Gwich’in",
	"Haida":	"Xaat Kíl",
	"Haitian Creole":	"Kreyòl ayisyen",
	"Hän":	"Häł gołan",
	"Harari":	"ሃራሪ",
	"Hausa":	" حَوْسَ",
	"Hawaiian":	"ʻōlelo Hawaiʻi",
	"Hebrew":	"עברית",
	"Herero":	"Otjiherero",
	"Hindi":	"हिन्दी ",
	"Hungarian":	"magyar / magyar nyelv",
	"Icelandic":	"Íslenska",
	"Igbo":	"igbo",
	"Ilocano":	"ilokano",
	"Indonesian":	"Bahasa Indonesia",
	"Ingush":	"гӀалгӀай мотт / ġalġay mott",
	"Inuktitut":	"ᐃᓄᒃᑎᑐᑦ ",
	"Iñupiaq":	"Inupiatun",
	"Irish": "An Ghaeilge",
	"Italian":	"italiano",
	"Japanese":	"日本語 ",
	"Javanese":	"basa Jawa",
	"Jersey Norman":	"Jèrriais",
	"Kabardian":	"къэбэрдеибзэ ",
	"Kabyle":	"Taqbaylit / ثاقبايليث",
	"Kaingang":	"kanhgág",
	"Kannada":	"ಕನ್ನಡ ",
	"Kanuri":	"kanuri",
	"Kapampangan":	"Kapampangan",
	"Karakalpak":	"қарақалпақ тили ",
	"Karelian":	"Karjalan kieli",
	"Kashmiri":	"कॉशुर / كٲشُر",
	"Kashubian":	"kaszëbsczi jãzëk",
	"Kazakh":	"Қазақ тілі / Qazaq tili / قازاق ٴتىلى",
	"Khakas":	"Хакас тілі / Khakas tîlî",
	"Khmer":	"ភាសាខ្មែរ ",
	"Khoekhoe":	"Khoekhoegowab / Nama",
	"Kikuyu":	"Gĩkũyũ",
	"Kinyarwanda":	"Ikinyarwanda",
	"Kiribati":	"taetae ni Kiribati",
	"Kirundi":	"íkiRǔndi",
	"Komi":	"коми кыв ",
	"Kongo":	"kikongo",
	"Konkani":	"कोंकणी ",
	"Korean":	"한국어  ",
	"Kumyk":	"Къумукъ тил",
	"Kurdish":	"Kurdí / کوردی / к’öрди",
	"Kven":	"Kainun kieli",
	"Kwanyama":	"kuanyama",
	"Kyrgyz":	"قىرعىز ",
	"Ladin":	"Ladin",
	"Ladino":	" ג’ודיאו‮–‬איספאניי",
	"Lahnda":	"ਲਹਿੰਦੀ ",
	"Lakota":	"Lakȟótiyapi",
	"Lao":	"ພາສາລາວ ",
	"Latin":	"Lingua Latina",
	"Latvian":	"latviešu valoda",
	"Laz":	"ლაზური ნენა / Lazuri nena",
	"Lezgian":	"лезги чӀал ",
	"Limburgish":	"Lèmburgs",
	"Lingala":	"lingála",
	"Lithuanian":	"lietuvių kalba",
	"Livonian":	"Līvõ kēļ",
	"Lombard":	"Lombard / Lumbaart",
	"Low German/Low Saxon":	"Plattdüütsch / Nedderdüütsch / Neddersassisch",
	"Luo":	"Dholuo",
	"Luxembourgish":	"Lëtzebuergesch",
	"Maasai/Maa":	"ɔl Maa",
	"Macedonian":	"македонски ",
	"Maldivian":	"ދިވެހި ",
	"Maithili":	"मैथिली ",
	"Malagasy":	"Fiteny Malagasy",
	"Malay":	"Bahasa melayu",
	"Malayalam":	"മലയാളം ",
	"Maltese":	"Malti",
	"Mandinka":	"Mandingo / لغة مندنكا",
	"Manipuri":	"মৈইতৈইলোন",
	"Mansi":	"Маньси ",
	"Manx":	"Gaelg/Gailck  / Yn Ghaelg / Y Ghailck",
	"Māori":	"te Reo Māori",
	"Marathi":	"मराठी ",
	"Mari/Cheremis":	"марий йылме ",
	"Marshallese":	"Kajin M̧ajeļ / Kajin Majōl",
	"Menominee":	"Mamaceqtaw",
	"Mirandese":	"lhéngua mirandesa",
	"Mohawk":	"Kanien’keha",
	"Moksha":	"мокшень кяль ",
	"Moldovan":	"лимба молдовеняскэ ",
	"Mongolian":	"монгол ",
	"Montagnais":	"Innu-Aimun",
	"Nahuatl":	"nāhuatl / nawatlahtolli",
	"Naskapi":	"ᓇᔅᑲᐱ  / Innu Aimun",
	"Nauru":	"Ekakairũ Naoero",
	"Navajo":	"Diné Bizaad / Dinék’ehjí",
	"Occitan":	"Occitan",
	"Oshiwambo":	"OshiWambo",
	"Nepali":	"नेपाली ",
	"Newari":	"नेपाल भाषा ",
	"Niuean":	"ko e vagahau Niuē / faka-Niue",
	"Nogai":	"ногай тили ",
	"Noongar":	"Nyungaa-wangka",
	"Northern Sotho":	"Sesotho sa Leboa",
	"Norwegian":	"Norsk",
	"Nyamwezi":	"kinyamwezi",
	"Nyoro":	"runyoro",
	"Ojibwe":	"ᐊᓂᔑᓇᐯᒧᐏᐣ ",
	"O’odham":	"O’odham ñiok",
	"Oriya":	"ଓଡ଼ିଆ ",
	"Oromo":	"Afaan Oromo",
	"Ossetian":	"ирон ӕвзаг ",
	"Palauan":	"tekoi ra Belau",
	"Pali":	"पालि ",
	"Papiamento":	"Papiamentu",
	"Pashto":	" پښتو",
	"Persian":	"فارسى",
	"Piedmontese":	"Piemonteis",
	"Polish":	"polski",
	"Portuguese":	"português",
	"Punjabi":	"ਪੰਜਾਬੀ / ﺏﺎﺠﻨﭘ ",
	"Quechua":	"Qhichwa",
	"Raga":	"Raga",
	"Rapanui":	"rapanui / pepito ote henua",
	"Rarotongan":	"Māori Kūki ‘Āirani / reo ipukarea",
	"Romanian":	"limba română / român",
	"Romansh":	"rumantsch",
	"Romani":	"रोमानो ",
	"Rotuman":	"Faeag Rotuma",
	"Russian":	"Русский",
	"Ruthenian":	"Rusyn / Русин",
	"Sámi ":	"anarâškielâ",
	"Sámi ":	"Кӣллт са̄мь кӣлл",
	"Sámi ":	"julevsámegiella",
	"Sámi ":	"davvisámegiella / sámegiellaa",
	"Sámi ":	"bidumsámegiella",
	"Sámi ":	"Sääˊmǩiõll / Nuõrttsää’m",
	"Sámi ":	"Åarjelsaemien gïele",
	"Sámi ":	"Са̄мь кӣлл / saa’mekiill",
	"Sámi ":	"Ubmejensámien giella",
	"Santali":	"संथाली ",
	"Samoan":	"Gagana Samoa",
	"Sango":	"Yângâ tî Sängö",
	"Sanskrit":	"संस्कृतम् ",
	"Sardinian":	"Limba Sarda / sardu",
	"Sark Norman":	"Sèrtchais / Serquiaise",
	"Scots":	"Scoats leid / Lallans",
	"Scottish Gaelic":	"Gàidhlig  / a’ Ghàidhlig",
	"Selkup":	"шӧльӄумыт әты ",
	"Serbian":	"српски ",
	"Shavante":	"aʼuwẽ mreme",
	"Shawnee":	"Sawanwa",
	"Shona":	"chiShona",
	"Shor":	"Шор тили ",
	"Sicilian":	"sicilianu",
	"Sidamo":	"Sidámo ‘Afó",
	"Silesian":	"ślůnsko godka / ślůnski",
	"Sindhi":	" سنڌي",
	"Sinhala":	"සිංහල ",
	"Silt’e":	"ስልጥኘ",
	"Slovak":	"slovenčina",
	"Slovenian":	"slovenščina",
	"Somali":	"af Soomaali",
	"Soninke":	"soninkanxaane",
	"Sorbian ":	"dolnoserbski",
	"Sorbian ":	"hornjoserbsce",
	"Southern Sotho":	"seSotho",
	"South Slavey":	"ᑌᓀ ᒐ ",
	"Spanish":	"español",
	"Sundanese":	"Basa Sunda",
	"Svan":	"ლუშნუ ნინ ",
	"Swabish":	"Schwäbisch",
	"Swahili":	"Kiswahili",
	"Swati":	"siSwati",
	"Swedish":	"Svenska",
	"Swiss German":	"Schwyzerdütsch",
	"Syriac":	" ܠܫܵܢܵܐ ܣܘܪܝܝܐ",
	"Tabassaran":	"табасаран чIал ",
	"Tagalog":	"Tagalog",
	"Tahitian":	"te reo tahiti / te reo Māʼohi",
	"Tai Nüa":	"ᥖᥭᥰᥖᥬᥳᥑᥨᥒᥰ",
	"Tajik":	"тоҷики / toçikī / تاجيكي",
	"Tamil":	"தமிழ் ",
	"Tatar":	"татарча / tatar tele / تاتارچا ",
	"Telugu":	"తెలుగు ",
	"Tetum":	"Tetun, Lia-Tetun",
	"Thai":	"ภาษาไทย ",
	"Tibetan":	"བོད་སྐད་ ",
	"Tigre":	"ትግረ ",
	"Tigrinya":	"ትግርኛ ",
	"Tlingit":	"Lingít",
	"Tok Pisin":	"Tok Pisin",
	"Tonga":	"chiTonga",
	"Tongan":	"Faka-Tonga / lea fakatonga",
	"Tsez":	"цез мец ",
	"Tsonga":	"xiTsonga",
	"Tswana":	"Setswana",
	"Tumbuka":	"chiTumbuka",
	"Turkish":	"Türkçe",
	"Turkmen":	"түркmенче ",
	"Tuscarora":	"Sgarooreh’ / Skarù∙rę’",
	"Tuvaluan":	"Te ‘gana Tūvalu",
	"Tuvan":	"Тыва дыл / Tyva dyl",
	"Twi":	"twi",
	"Udmurt":	"удмурт кыл ",
	"Ukrainian":	"Українська ",
	"Urdu":	" اردو",
	"Uyghur":	"Уйғур /ئۇيغۇر ",
	"Uzbek":	"أۇزبېك ﺗﻴﻠی o’zbek tili ўзбек тили ",
	"Venda":	"tshiVenḓa",
	"Venetian":	"vèneto",
	"Veps":	"vepsän kel’",
	"Vietnamese":	"tiếng việt ",
	"Võro":	"võro kiilʼ",
	"Votic":	"Vadjaa tšeeli",
	"Walloon":	"walon",
	"Waray-Waray":	"Wáray-Wáray",
	"Welsh":	"Cymraeg / Y Gymraeg",
	"Wiradjuri":	"Wirraayjuurray / Wirraaydhuurray",
	"Wolof":	"Wollof",
	"Xamtanga":	"ኃምታጛ",
	"Xhosa":	"isiXhosa",
	"Yakut Sakha":	"саха тыла",
	"Yi":	"ꆇꉙ",
	"Yiddish":	"ײִדיש",
	"Yindjibarndi":	"Indjibandi",
	"Yolngu":	"Yolŋu matha",
	"Yoruba":	"Yorùbá",
	"Yupik":	"Yup’ik/Юпик",
	"Zhuang":	"Vaƅcueŋƅ / Vahcuengh",
	"Zulu":	"isiZulu",
	"Zuñi":	"Shiwi’ma",
}